package dev.lunynt.opengate.database;

import java.sql.Connection;
import java.sql.SQLException;

public final class DatabaseSchema {
    private DatabaseSchema() {}

    public static void migrate(OpenGateDataSource dataSource) {
        if (dataSource.type() == DatabaseType.SQLITE) {
            migratePortable(dataSource, "INTEGER PRIMARY KEY AUTOINCREMENT");
        } else {
            var identity = switch (dataSource.type()) {
                case POSTGRESQL -> "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
                case MYSQL, MARIADB -> "BIGINT AUTO_INCREMENT PRIMARY KEY";
                case H2 -> "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
                case SQLITE -> throw new AssertionError();
            };
            migratePortable(dataSource, identity);
        }
    }

    private static void migratePortable(OpenGateDataSource dataSource, String identityColumn) {
        try (var connection = dataSource.getConnection()) {
            if (dataSource.type() == DatabaseType.SQLITE) {
                try (var statement = connection.createStatement()) {
                    statement.execute("PRAGMA journal_mode=WAL");
                }
            }
            connection.setAutoCommit(false);
            try {
                if (dataSource.type() == DatabaseType.SQLITE) SqliteSchema.migrate(connection);
                createTables(connection, identityColumn);
                connection.commit();
            } catch (SQLException exception) {
                connection.rollback();
                throw exception;
            }
        } catch (SQLException exception) {
            throw new IllegalStateException("could not migrate OpenGate database", exception);
        }
    }

    private static void createTables(Connection connection, String identityColumn) throws SQLException {
        try (var statement = connection.createStatement()) {
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS accounts (
                        player_id VARCHAR(36) PRIMARY KEY NOT NULL,
                        username VARCHAR(64) NOT NULL,
                        normalized_username VARCHAR(64) UNIQUE NOT NULL,
                        identity_type VARCHAR(32) NOT NULL,
                        password_hash VARCHAR(512),
                        totp_secret VARCHAR(1024),
                        session_generation BIGINT NOT NULL DEFAULT 0,
                        created_at BIGINT NOT NULL
                    )
                    """);
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS audit_events (id " + identityColumn + ", "
                    + "occurred_at BIGINT NOT NULL, event_type VARCHAR(64) NOT NULL, player_id VARCHAR(36), "
                    + "username VARCHAR(64), address_fingerprint VARCHAR(128), detail VARCHAR(256))");
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS totp_replay (
                        player_id VARCHAR(36) PRIMARY KEY NOT NULL,
                        last_step BIGINT NOT NULL,
                        FOREIGN KEY (player_id) REFERENCES accounts(player_id) ON DELETE CASCADE
                    )
                    """);
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS identity_mappings (
                        source_id VARCHAR(36) PRIMARY KEY NOT NULL,
                        translated_id VARCHAR(36) UNIQUE NOT NULL,
                        created_at BIGINT NOT NULL
                    )
                    """);
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS login_sessions (
                        token_hash VARCHAR(64) PRIMARY KEY NOT NULL,
                        player_id VARCHAR(36) NOT NULL,
                        credential_fingerprint VARCHAR(64) NOT NULL,
                        session_generation BIGINT NOT NULL,
                        created_at BIGINT NOT NULL,
                        expires_at BIGINT NOT NULL,
                        FOREIGN KEY (player_id) REFERENCES accounts(player_id) ON DELETE CASCADE
                    )
                    """);
            if (!columnExists(connection, "login_sessions", "credential_fingerprint")) {
                statement.executeUpdate("ALTER TABLE login_sessions ADD COLUMN "
                        + "credential_fingerprint VARCHAR(64) NOT NULL DEFAULT ''");
            }
            if (!columnExists(connection, "accounts", "session_generation")) {
                statement.executeUpdate("ALTER TABLE accounts ADD COLUMN "
                        + "session_generation BIGINT NOT NULL DEFAULT 0");
            }
            if (!columnExists(connection, "login_sessions", "session_generation")) {
                statement.executeUpdate("ALTER TABLE login_sessions ADD COLUMN "
                        + "session_generation BIGINT NOT NULL DEFAULT 0");
            }
            createIndex(connection, statement, "login_sessions", "login_sessions_player",
                    "CREATE INDEX login_sessions_player ON login_sessions(player_id)");
            createIndex(connection, statement, "login_sessions", "login_sessions_expiry",
                    "CREATE INDEX login_sessions_expiry ON login_sessions(expires_at)");
            createIndex(connection, statement, "audit_events", "audit_events_player_time",
                    "CREATE INDEX audit_events_player_time ON audit_events(player_id, occurred_at)");
            createIndex(connection, statement, "audit_events", "audit_events_type_time",
                    "CREATE INDEX audit_events_type_time ON audit_events(event_type, occurred_at)");
        }
    }

    private static void createIndex(
            Connection connection, java.sql.Statement statement, String tableName, String indexName, String sql)
            throws SQLException {
        if (indexExists(connection, tableName, indexName)
                || indexExists(connection, tableName.toUpperCase(java.util.Locale.ROOT), indexName)) return;
        statement.executeUpdate(sql);
    }

    private static boolean indexExists(Connection connection, String tableName, String indexName) throws SQLException {
        try (var indexes = connection.getMetaData().getIndexInfo(null, null, tableName, false, false)) {
            while (indexes.next()) {
                var existing = indexes.getString("INDEX_NAME");
                if (existing != null && existing.equalsIgnoreCase(indexName)) return true;
            }
            return false;
        }
    }

    private static boolean columnExists(Connection connection, String tableName, String columnName) throws SQLException {
        for (var candidate : new String[] {tableName, tableName.toUpperCase(java.util.Locale.ROOT)}) {
            try (var columns = connection.getMetaData().getColumns(null, null, candidate, null)) {
                while (columns.next()) {
                    if (columnName.equalsIgnoreCase(columns.getString("COLUMN_NAME"))) return true;
                }
            }
        }
        return false;
    }
}
