package dev.lunynt.opengate.audit;

public enum AuditEventType {
    REGISTRATION,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGIN_RATE_LIMITED,
    TOTP_FAILURE,
    PASSWORD_CHANGED,
    ACCOUNT_DELETED,
    TOTP_ENABLED,
    TOTP_DISABLED,
    ADMIN_ACCOUNT_LOOKUP,
    ADMIN_AUDIT_VIEWED,
    ADMIN_SESSION_REVOKED
}
