name: build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spigot-api:
          - 1.21-R0.1-SNAPSHOT
          - 26.2-R0.1-SNAPSHOT
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '25'
      - uses: gradle/actions/setup-gradle@v6
        with:
          validate-wrappers: true
      - run: ./gradlew clean build --no-daemon -PspigotApiVersion=${{ matrix.spigot-api }}
